import type { PersonalityResult } from './gemini'

function MoodBar({ score }: { score: number }) {
  const color =
    score >= 70 ? 'from-fuchsia-500 to-cyan-400' :
    score >= 40 ? 'from-amber-500 to-fuchsia-400' :
    'from-red-500 to-amber-400'
  return (
    <div className="w-full h-3 bg-white/5 rounded-full overflow-hidden border border-white/10">
      <div
        className={`h-full rounded-full bg-gradient-to-r ${color} transition-all duration-1000`}
        style={{ width: `${score}%` }}
      />
    </div>
  )
}

export default function Card({ username, result }: { username: string; result: PersonalityResult }) {
  return (
    <div className="poster-grid card-glow border border-white/10 rounded-2xl p-8 sm:p-10 relative overflow-hidden">
      {/* Decorative corner brackets */}
      <div className="absolute top-4 left-4 text-fuchsia-400/40 font-pixel text-2xl">╔══</div>
      <div className="absolute top-4 right-4 text-fuchsia-400/40 font-pixel text-2xl">══╗</div>
      <div className="absolute bottom-4 left-4 text-fuchsia-400/40 font-pixel text-2xl">╚══</div>
      <div className="absolute bottom-4 right-4 text-fuchsia-400/40 font-pixel text-2xl">══╝</div>

      {/* Username */}
      <div className="text-center mb-6">
        <div className="text-fuchsia-400/50 font-pixel text-sm mb-1">PATIENT PROFILE</div>
        <h2 className="font-retro text-xl sm:text-2xl text-white glitch">@{username}</h2>
      </div>

      {/* Personality Type */}
      <div className="text-center mb-6">
        <div className="inline-block px-4 py-2 bg-fuchsia-500/10 border border-fuchsia-500/30 rounded-lg mb-2">
          <span className="font-pixel text-cyan-300 text-sm">CODING PERSONALITY</span>
        </div>
        <h3 className="font-retro text-lg sm:text-xl text-fuchsia-300 leading-relaxed">
          {result.type}
        </h3>
        <p className="font-pixel text-cyan-300/70 text-sm mt-1">{result.subtitle}</p>
      </div>

      {/* Mood Score */}
      <div className="mb-6">
        <div className="flex justify-between items-center mb-2">
          <span className="font-pixel text-cyan-300 text-sm">MOOD SCORE</span>
          <span className="font-retro text-lg text-white">
            {result.moodScore}%
          </span>
          <span className="font-pixel text-fuchsia-300 text-sm">{result.moodLabel}</span>
        </div>
        <MoodBar score={result.moodScore} />
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-3 gap-3 mb-6">
        <div className="bg-white/5 rounded-lg p-3 text-center border border-white/5">
          <div className="font-retro text-lg text-fuchsia-300">{result.stats.totalCommits}</div>
          <div className="font-pixel text-xs text-gray-500 mt-1">COMMITS</div>
        </div>
        <div className="bg-white/5 rounded-lg p-3 text-center border border-white/5">
          <div className="font-retro text-lg text-cyan-300">{result.stats.peakHour}</div>
          <div className="font-pixel text-xs text-gray-500 mt-1">PRIME TIME</div>
        </div>
        <div className="bg-white/5 rounded-lg p-3 text-center border border-white/5">
          <div className="font-retro text-lg text-fuchsia-300">{result.stats.favoriteDay}</div>
          <div className="font-pixel text-xs text-gray-500 mt-1">FAVORITE DAY</div>
        </div>
      </div>

      {/* Top Commits */}
      <div className="mb-6">
        <div className="text-center mb-3">
          <span className="font-pixel text-cyan-300/50 text-xs">CONFESSIONAL — TOP OFFENSES</span>
        </div>
        {result.topCommits.map((msg, i) => (
          <div key={i} className="bg-white/[0.03] border border-white/[0.06] rounded-lg p-3 mb-2">
            <div className="flex items-start gap-2">
              <span className="font-pixel text-fuchsia-400 text-lg mt-0.5">#{i + 1}</span>
              <span className="font-pixel text-white/80 text-sm leading-relaxed">&ldquo;{msg}&rdquo;</span>
            </div>
          </div>
        ))}
      </div>

      {/* Diagnosis */}
      <div className="mb-4 p-4 bg-cyan-500/5 border border-cyan-500/20 rounded-lg">
        <div className="font-pixel text-cyan-300 text-xs mb-2">DIAGNOSIS</div>
        <p className="font-pixel text-white/70 text-sm leading-relaxed">{result.diagnosis}</p>
      </div>

      {/* Prescription */}
      <div className="p-4 bg-fuchsia-500/5 border border-fuchsia-500/20 rounded-lg">
        <div className="font-pixel text-fuchsia-300 text-xs mb-2">PRESCRIPTION</div>
        <p className="font-pixel text-white/70 text-sm leading-relaxed">{result.prescription}</p>
      </div>

      {/* Footer */}
      <div className="mt-6 pt-4 border-t border-white/5 text-center">
        <span className="font-pixel text-[8px] text-gray-600">
          GENERATED BY COMMITCONFESSIONS — your sins are valid
        </span>
      </div>
    </div>
  )
}
